#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         GraphViz-Data-Structure
version:      0.11
version_from: lib/GraphViz/Data/Structure.pm
installdirs:  site
requires:
    GraphViz:                      2.01
    Test::More:                    0
    Devel::Peek:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
