#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         GraphViz-Data-Structure
version:      0.09
version_from: lib/GraphViz/Data/Structure.pm
installdirs:  site
requires:
    Devel::Peek:                   0
    Test::More:                    0
    GraphViz:                      1.3

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
